# Generated by Django 4.2.4 on 2023-08-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('product', models.CharField(default='not specified', max_length=140)),
                ('imageurl', models.CharField(default='not specified', max_length=140)),
                ('title', models.CharField(default='not specified', max_length=140)),
            ],
        ),
    ]
